interface ModDesc
{
	title: string,
	desc: string,
	group: number | number[],
	imgs: string[],
}
export interface ModGroup
{
	id: number,
	title: string,
}

export const G: ModGroup[] = [
	{ id: 1, title: "Генерация мира" },
	{ id: 7, title: "Магия" },
	{ id: 6, title: "Техника" },
	{ id: 4, title: "Полезные предметы" },
	{ id: 3, title: "Улучшения" },
	{ id: 5, title: "Декор" },
	{ id: 2, title: "Интерфейс" },

	// { id: 0, title: "Остальное" },
]

export const Mods: ModDesc[] = [
	{ title: "Biomes O' Plenty", group: 1, desc: "Добавляет новые биомы", imgs: ["biomesoplenty.png"] },
	{ title: "Ecologics", group: 1, desc: "Оживляет биомы", imgs: ["ecologics.jpg"] },
	{ title: "Verdure", group: 1, desc: "Камни, цветочки, грибы", imgs: ["verdure.jpg"] },
	{ title: "Goblin Traders", group: 1, desc: "Гоблины-торговцы", imgs: ["goblins.png"] },

	{ title: "OptiFine", group: 2, desc: "", imgs: [] },
	{ title: "Just Enough Items", group: 2, desc: "Список предметов и их рецепты", imgs: [] },
	{ title: "Just Enough Resources", group: 2, desc: "Информация о раположении руд (дополнение к JEI)", imgs: [] },
	{ title: "The One Probe", group: 2, desc: "Инфо о блоке", imgs: ["The_One_Probe.png"] },
	{ title: "JourneyMap", group: 2, desc: "Мини-карта", imgs: [] },
	{ title: "MouseTweaks", group: 2, desc: "Упрощение перемещения предметов в инвентаре", imgs: [] },
	{ title: "AppleSkin", group: 2, desc: "Показывает сколько прибавится сытости от еды в руке", imgs: [] },
	{ title: "TrashSlot", group: 2, desc: "Слот-мусорка в инвентаре", imgs: [] },
	{ title: "Inventory Sorter", group: 2, desc: "Сортирует инвентарь", imgs: [] },
	{ title: "Skin Layers 3D", group: 2, desc: "Делает второй слой скина объёмным", imgs: ["3dskin.jpg"] },
	{ title: "СustomSkinLoader", group: 2, desc: "Скины на offline сервере", imgs: [] },
	{ title: "Mod Name Tooltip", group: 2, desc: "Показывает из какого мода предмет", imgs: [] },
	{ title: "Polymorph", group: 2, desc: "Решает конфликты рецетов", imgs: [] },
	{ title: "JEI Integration", group: 2, desc: "Дополнение к JEI", imgs: [] },

	{ title: "Hand Over Your Items", group: 3, desc: "Дать предмет игроку с помощью shift + ПКМ", imgs: [] },
	{ title: "Cosmetic Armor", group: 3, desc: "Возможность быть в одной броне, а выглядеть как в другой", imgs: [] },
	{ title: "Enigmatic Graves", group: 3, desc: "На месте смерти появляется могила со всеми вещами", imgs: [] },
	{ title: "Spice of Life: Carrot Edition", group:3, desc: "Усиления при разнообразном питании", imgs: [] },
	{ title: "Actually Useful Stonecutter", group: 3, desc: "Камнерез может пилить и дерево", imgs: [] },
	{ title: "Apotheosis", group: 3, desc: "Изменён стол зачарований, сбор спавнера с помощью шёлкового касания, улучшение спавнеров, улучшены торги жителей.", imgs: [] },
	{ title: "Carry On", group: 3, desc: "Возможность носить сундуки и животных на руках", imgs: ["carryon.png"] },
	{ title: "Improved Vanilla", group: 3, desc: "Пересадить грядку после созревания с помощью ПКМ, и несколько изменений рецептов", imgs: [] },
	{ title: "Sit", group: 3, desc: "Возможночть сидеть на ступеньках и полублоках", imgs: [] },
	{ title: "Curios", group: 3, desc: "Слоты в инвентаре для талисманов, рюкзаков и прочего", imgs: [] },
	{ title: "DoubleDoors", group: 3, desc: "Двойные двери открываются вместе", imgs: [] },
	{ title: "AmbientSounds", group: 3, desc: "Добавляет звуки окружения: птички, сверчки и т.д.", imgs: [] },
	{ title: "Sound Physics", group: 3, desc: "Улучшеная физика звука", imgs: [] },
	{ title: "ItemPhysic", group: 3, desc: "Физика для предметов", imgs: [] },
	{ title: "Snow! Real Magic! ⛄", group: 3, desc: "Улучшенный снег", imgs: [] },
	{ title: "FallingTree", group: 3, desc: "Дерево падает при рубке", imgs: [] },
	{ title: "Falling Leaves", group: 3, desc: "С деревьев падают листья", imgs: [] },
	{ title: "Fast Leaf Decay", group: 3, desc: "Листья дерева быстро опадают", imgs: [] },
	{ title: "Serene Seasons", group: 3, desc: "Времена года", imgs: [] },
	{ title: "Quark", group: 3, desc: "Всякие улучшения", imgs: [] },

	{ title: "Tinkers Construct", group: 4, desc: "Инструменты", imgs: [] },
	{ title: "Cyclic", group: 4, desc: "Предметы, зачарования, зелья, механизмы", imgs: [] },
	{ title: "Sleeping Bags", group: 4, desc: "Спальные мешки для сна без спавнпоинта", imgs: [] },
	{ title: "Iron Jetpacks", group: 4, desc: "Джет-паки", imgs: [] },
	{ title: "Iron Chests", group: 4, desc: "Сундуки большего размера", imgs: [] },
	{ title: "Storage Drawers", group: 4, desc: "Ящики для хранения ресурсов", imgs: [] },
	{ title: "Simple Storage Network", group: 4, desc: "Доступ ко всем ресурсам через один терминал", imgs: [] },
	{ title: "OpenBlocks Elevator", group: 4, desc: "Лифты", imgs: [] },
	{ title: "Simply Backpacks", group: 4, desc: "Рюкзаки", imgs: [] },
	{ title: "Nature's Compass", group: 4, desc: "Компас биомов", imgs: [] },
	{ title: "Waystones", group: 4, desc: "Путевые камни для быстрого перемещения", imgs: [] },
	{ title: "Travel Anchors", group: 4, desc: "Короткие телепорты", imgs: [] },
	{ title: "XP Tome", group: 4, desc: "Книга для хранения опыта", imgs: [] },
	{ title: "Akashic Tome", group: 4, desc: "Книга для хранения книг", imgs: [] },
	{ title: "Trashcans", group: 4, desc: "Мусорки", imgs: [] },
	{ title: "Advanced Netherite", group: 4, desc: "Незеритовые предметы можно улучшить", imgs: [] },

	{ title: "Chisels & Bits", group: 5, desc: "Возможность строить из вокселей", imgs: [] },
	{ title: "Macaw's Bridges", group: 5, desc: "Мосты и лестнецы", imgs: [] },
	{ title: "Macaw's Doors", group: 5, desc: "Двери", imgs: [] },
	{ title: "Macaw's Fences and Walls", group: 5, desc: "Заборы", imgs: [] },
	{ title: "Macaw's Furniture", group: 5, desc: "Мебель", imgs: [] },
	{ title: "Macaw's Lights and Lamps", group: 5, desc: "Лампы", imgs: [] },
	{ title: "Macaw's Paintings", group: 5, desc: "Картины", imgs: [] },
	{ title: "Macaw's Roofs", group: 5, desc: "Крыши", imgs: [] },
	{ title: "Macaw's Trapdoors", group: 5, desc: "Люки", imgs: [] },
	{ title: "Macaw's Windows", group: 5, desc: "Окна", imgs: [] },


	{ title: "Immersive Engineering", group: 6, desc: "", imgs: ["imersive.png"] },
	{ title: "Mekanism", group: 6, desc: "", imgs: ["mekanism.png"] },
	{ title: "Create", group: 6, desc: "", imgs: ["create.jpg"] },
	{ title: "Little Logistics", group: 6, desc: "Поезда и лодки для перемещения ресурсов", imgs: ["littlelogistics.png"] },

	{ title: "Nature's Aura", group: 7, desc: "Магические ритуалы, алтари, взаимодействие с аурой природы", imgs: ["NaturesAura.png"] },
	{ title: "Forbidden and Arcanus", group: 7, desc: "Магические аксессуары, предметы, блоки и оружие", imgs: [] },
	{ title: "Ars Nouveau", group: 7, desc: "Создание заклинаний, ритуалы и помощники", imgs: ["ars_nouveau.png"] },
	{ title: "ProjectE", group: 7, desc: "Алхимия, превращение одного в другое, кольцо полёта", imgs: ["ProjectE.png"] },
	{ title: "Mystical Agriculture", group: 7, desc: "Выращивание ресурсов", imgs: ["mysticalagriculture.png"] },
]